### ISSUE TITLE
Added your parser to network-automation/cisco_ios_command_parsers

### ISSUE THREAD

**Issue by joubbi** [kvernNC/cisco_config_parser#1]
Hi,

Thank you for sharing your work!

I added a link to your cisco_config_parser on this page:
https://github.com/network-automation/cisco_ios_command_parsers

I hope it's ok. I was looking for parsers before I started creating my own, in order to not need to reinvent the wheel. That list is my attempt to help others in the same situation.

Let me know if you don't want your parser to be listed there for some reason. I will then remove it if you're not able to do it yourself.

**Comment by kvernNC** [comment]
It's fine for me, I wanted to share my work on this too, as I didn't find good example when I needed it.
